{% set data = load_file_data(RECIPE_DIR + '/../pyproject.toml') %}
{% set name = data['project']['name'] %}

package:
  name: {{ name }}
  version: {{ data['project']['version'] }}

source:
  path: ..

build:
  noarch: python
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  run_exports:
    - {{ pin_subpackage(name) }}
  script:
    - "{{ PYTHON }} -m pip install {{ SRC_DIR }} -vv"

requirements:
  host:
    - python {{ python }}
    - setuptools {{ setuptools }}
    - pip {{ pip }}
    - bob
    - bob.io.base
    - bob.bio.base
    - bob.bio.face
    - bob.pad.base
    - bob.bio.video
    - clapper {{ clapper }}
    - imageio-ffmpeg {{ imageio_ffmpeg }}
    - numpy {{ numpy }}
    - pytorch {{ pytorch }}
    - scikit-learn {{ scikit_learn }}
    - scikit-image {{ scikit_image }}
    - tensorflow {{ tensorflow }}
  run:
    - python
    - setuptools
    - bob
    - bob.io.base
    - bob.bio.base
    - bob.bio.face
    - bob.pad.base
    - bob.bio.video
    - {{ pin_compatible('clapper') }}
    - {{ pin_compatible('imageio-ffmpeg') }}
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('pytorch') }}
    - {{ pin_compatible('scikit-learn') }}
    - {{ pin_compatible('scikit-image') }}
  run_constrained:
    - {{ pin_compatible('tensorflow') }}  # [linux]
test:
  imports:
    - {{ name }}
  commands:
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]

about:
  home: {{ data['project']['urls']['homepage'] }}
  summary: {{ data['project']['description'] }}
  license: {{ data['project']['license']['text'] }}
  license_family: BSD
