{% set name = 'bob.pad.face' %}
{% set project_dir = environ.get('RECIPE_DIR') + '/..' %}

package:
  name: {{ name }}
  version: {{ environ.get('BOB_PACKAGE_VERSION', '0.0.1') }}

build:
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  run_exports:
    - {{ pin_subpackage(name) }}
  script:
    - cd {{ project_dir }}
    {% if environ.get('BUILD_EGG') %}
    - python setup.py sdist --formats=zip
    {% endif %}
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python {{ python }}
    - setuptools {{ setuptools }}
    - six {{ six }}
    - sphinx {{ sphinx }}
    - numpy {{ numpy }}
    - bob.extension
    - bob.bio.base
    - bob.io.base
    - bob.ip.base
    - bob.pad.base
    - bob.bio.face
    - bob.bio.video
    - bob.io.image
    - bob.ip.color
    - bob.ip.qualitymeasure
    - bob.learn.libsvm
  run:
    - python
    - setuptools
    - six
    - sphinx
    - numpy

test:
  imports:
    - {{ name }}
  commands:
    - nosetests --with-coverage --cover-package={{ name }} -sv {{ name }}
    - sphinx-build -aEW {{ project_dir }}/doc {{ project_dir }}/sphinx
    - sphinx-build -aEb doctest {{ project_dir }}/doc sphinx
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]
  requires:
    - bob-devel {{ bob_devel }}.*
    - nose
    - coverage
    - sphinx
    - sphinx_rtd_theme
    - gridtk
    - scikit-learn
    - bob.ip.dlib
    - bob.ip.facelandmarks
    - bob.db.replay

about:
  home: https://www.idiap.ch/software/bob/
  license: GNU General Public License v3 (GPLv3)
  summary: Implements tools for spoofing or presentation attack detection in face biometrics
  license_family: GPL
